### PR TITLE
Refactor/update linux pw

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/66)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/66)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java, line 462 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/66#-LxsPdhj5mokqvhhdz3f:-LxsPdhk0XGuZEmLcUtz:b6p0kf7) ([raw file](https://github.com/servicecatalog/oscm-app/blob/30f6a13da70812c7fbe4aa88e04dd3623601afcc/oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java#L462)):*
> ```Java
>             LOG.debug("");
> 
>             ScriptExecutionObjectReferences objectRef = getScriptExecutionObjectReferences(
> ```

Unit tests needed.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java, line 476 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/66#-LxsPnsJDjFcZJ3271du:-LxsPnsJDjFcZJ3271dv:b-89a4rb) ([raw file](https://github.com/servicecatalog/oscm-app/blob/30f6a13da70812c7fbe4aa88e04dd3623601afcc/oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java#L476)):*
> ```Java
>             LOG.debug("Successfully created a temporary file at: "
>                     + tempFilePath + " inside the guest");
>             GuestProgramSpec spec = getGuestProgramSpec(tempFilePath);
> ```

Dito.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/66)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java, line 462 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/66#-LxsPdhj5mokqvhhdz3f:-LxzTsaz7nD20a-dYskM:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/30f6a13da70812c7fbe4aa88e04dd3623601afcc/oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java#L462)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Unit tests needed.
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java, line 476 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/66#-LxsPnsJDjFcZJ3271du:-LxzTstV9ymdINEFBREb:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/30f6a13da70812c7fbe4aa88e04dd3623601afcc/oscm-app-vmware/src/main/java/org/oscm/app/vmware/business/Script.java#L476)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Dito.
</blockquote></details>

Done.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/66)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-app-vmware/src/test/java/org/oscm/app/vmware/business/ScriptTest.java, line 144 at r3](https://reviewable.io/reviews/servicecatalog/oscm-app/66#-LxzURYH87iG4blYJhn1:-LxzURYJ4C6pts__SJOp:b-te4eok) ([raw file](https://github.com/servicecatalog/oscm-app/blob/86b47ba9cea4b113fea61689d1f2aa0f15662f0d/oscm-app-vmware/src/test/java/org/oscm/app/vmware/business/ScriptTest.java#L144)):*
> ```Java
> 
>         // then
>         verify(script).initScript(vph, os, updateScript);
> ```

Sorry, I guess it's not of your change, but it just came to my eyes now. IMHO it's a bit of non-sense to call initScript an then verify same invocation. ;-)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/66)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-vmware/src/test/java/org/oscm/app/vmware/business/ScriptTest.java, line 144 at r3](https://reviewable.io/reviews/servicecatalog/oscm-app/66#-LxzURYH87iG4blYJhn1:-LxzmtxF8mm57YwoyP2H:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/86b47ba9cea4b113fea61689d1f2aa0f15662f0d/oscm-app-vmware/src/test/java/org/oscm/app/vmware/business/ScriptTest.java#L144)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Sorry, I guess it's not of your change, but it just came to my eyes now. IMHO it's a bit of non-sense to call initScript an then verify same invocation. ;-)
</blockquote></details>

Done.

**Pull request merged**
