### PR TITLE
Add code formatting

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Add code formatting and copyright headers when merging PRs
- Attach unit test and coverage report

**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [X] changes were tested manually
- [x] unit tests were properly implemented

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/130)

### CODE REVIEW

**Review by cworf91 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/130)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-aws/src/test/java/org/oscm/app/aws/EC2CommunicationTest.java, line 481 at r3](https://reviewable.io/reviews/servicecatalog/oscm-app/130#-MpCMBcIADF8bPoePCAp:-MpCMBcJ27kQ0TC8EB8w:baz5zf4) ([raw file](https://github.com/servicecatalog/oscm-app/blob/0aa24bd183632e096966f1bbc37e136d915a7f26/oscm-app-aws/src/test/java/org/oscm/app/aws/EC2CommunicationTest.java#L481)):*
> ```Java
>           .contains("cannot find the file")
>           || ape.getMessage().contains("No such file")
>               || ape.getMessage().contains("Reading userdata failed"));;
> ```

There are two semicolon

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/130)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-app-aws/src/test/java/org/oscm/app/aws/EC2CommunicationTest.java, line 481 at r3](https://reviewable.io/reviews/servicecatalog/oscm-app/130#-MpCMBcIADF8bPoePCAp:-MpCP1aV1I6-euq94ogA:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/0aa24bd183632e096966f1bbc37e136d915a7f26/oscm-app-aws/src/test/java/org/oscm/app/aws/EC2CommunicationTest.java#L481)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

There are two semicolon
</blockquote></details>

Done.

**Review by cworf91 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/130#-:-MpCPUG96gInK0QNkdRv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by cworf91 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/130#-:-MpCVJ4d1e5eUavGsBYZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by cworf91 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/130)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GoebelL)

**Pull request merged**
