### PR TITLE
Get email settings from service parameters

### LINKED ISSUE #97: Basic approval tool settings from appropriate source
**Summary**
Read basic approval tool setting for service parameters and configuration settings.

**Details**
1. Currently basic controller settings are expected as custom attributes from the approval tool subscription.
However there are basic settings which are not instance specific like for example the APPROVAL_URL. There is only _one_ APPROVAL_URL, because all approver users use same web application. 
 2. The BSS_WEBSERVICE_WSDL_URL setting is redundant with APP configuration settings. Remove this and load the URL via APPlatformService#getBSSWebServiceWSDLUrl
3. There maybe additional basics settings that are specific to each approval service instance, e.g. email settings and appearance of approver emails. Read these settings from service parameter of the approval tool service.  

**Acceptance criteria**
- [ ] APPROVAL_URL via configuration setting in the bssapp database.
- [ ] No superfluous settings remaining

**Additional context**
Point 1 requires a second PR to be started in the oscm-dockerbuild repo for setting default APPROVAL_URL via SQL init script.
Point 2 requires a second PR to be started in the oscm-approval repo to fix the callers for BSS_WEBSERVICE_WSDL_URL.

### PR DESCRIPTION
**Pull request by GoebelL**
**Changes in this Pull Request:**
- Remove need of WSDL URL as custom attribute and instead obtain this URL from APP internally, using APPlatformService. 
- Allow the supplier admin as owner of the approval process to provide email settings for the approval tool via service parameters.

**Mandatory checks:**
- [X] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [ ] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
Not yet

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/100)

### CODE REVIEW

**Review by cworf91 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/100)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-app-approval/src/main/java/org/oscm/app/approval/controller/ApprovalInstanceAccess.java, line 164 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/100#-MKFa22bEWT_TuTocAaX:-MKFa22bEWT_TuTocAaY:b-7u85x7) ([raw file](https://github.com/servicecatalog/oscm-app/blob/8050c2329b6c9e8e80a5c6709f61b766bcd31145/oscm-app-approval/src/main/java/org/oscm/app/approval/controller/ApprovalInstanceAccess.java#L164)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
>    return     hashMap
>             .entrySet()
>             .stream()
>             .collect(
>                 Collectors.toMap(
>                     e -> e.getKey(),
>                     e -> ((e.getValue() == null) ? null : e.getValue().getValue())));
> ```
</details>

**Review by cworf91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/100#-:-MKFazko8Enkp4V6tIpU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

**Review by GoebelL — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/100)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91 and @kowalczyka)

___
*[oscm-app-approval/src/main/java/org/oscm/app/approval/controller/ApprovalInstanceAccess.java, line 164 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/100#-MKFa22bEWT_TuTocAaX:-MKFjnz76CYaxVqHI03j:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/8050c2329b6c9e8e80a5c6709f61b766bcd31145/oscm-app-approval/src/main/java/org/oscm/app/approval/controller/ApprovalInstanceAccess.java#L164)):*
<details><summary><i>Previously, cworf91 (cworf91) wrote…</i></summary><blockquote>

> ```
>    return     hashMap
>             .entrySet()
>             .stream()
>             .collect(
>                 Collectors.toMap(
>                     e -> e.getKey(),
>                     e -> ((e.getValue() == null) ? null : e.getValue().getValue())));
> ```

</blockquote></details>

Done.

**Review by cworf91 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/100#-:-MKFkUkxBCQptgYMxQQb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by kowalczyka — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/100#-:-MKJRFGw6SJZP04XByK3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
