### PR TITLE
Gather usage data

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/37)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/37)* status: 7 of 10 files reviewed, 9 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/resources/TechnicalService_Event.xml, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLTJs_4LoRIkXkB4EQ:-LjLTJs_4LoRIkXkB4ER:bwu0bzx) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/resources/TechnicalService_Event.xml#L5)):*
> ```XML
> 
> <tns:TechnicalServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="oscm.serviceprovisioning/1.9/TechnicalService.xsd ../../oscm-serviceprovisioning/javares/TechnicalServices.xsd" xmlns:tns="oscm.serviceprovisioning/1.9/TechnicalService.xsd">
>   <tns:TechnicalService accessType="DIRECT" allowingOnBehalfActing="false" baseUrl="" billingIdentifier="NATIVE_BILLING" build="2017-09-07" id="VMwareTest" loginPath="/" onlyOneSubscriptionPerUser="false" provisioningPassword="" provisioningType="ASYNCHRONOUS" provisioningUrl="http://oscm-app:8880/oscm-app/webservices/oscm-app/oscm-app/org.oscm.app.v2_0.service.AsynchronousProvisioningProxy?wsdl" provisioningUsername="" provisioningVersion="1.0">
> ```

Let's use speaking ID, like WMwareSampleWithEvents
___
*[oscm-app-vmware/resources/TechnicalService_Event.xml, line 916 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLU2Cx6B4OF1_KTWDG:-LjLU2CyATGG3tXasKY_:bnh9qzs) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/resources/TechnicalService_Event.xml#L916)):*
> ```XML
>     </Operation>
>   </tns:TechnicalService>
>   <tns:TechnicalService accessType="DIRECT" allowingOnBehalfActing="false" baseUrl="" billingIdentifier="NATIVE_BILLING" build="2017-09-07" id="VMware ESS 6.5 17.4 test1" loginPath="/" onlyOneSubscriptionPerUser="false" provisioningPassword="" provisioningType="ASYNCHRONOUS" provisioningUrl="https://eststbesint.intern.est.fujitsu.com:8881/ProvisioningService/AsynchronousProvisioningProxy?wsdl" provisioningUsername="" provisioningVersion="1.0">
> ```

While looking to the naming, let's fix this name as well. I suggest id="VMware 6.5 Sample" (anything elso ok, but without OSCM version number)
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_eWq4Xec4R7P1GVW:-LjL_eWrBTk8foUCAkWm:bixeyxv) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L1)):*
> ```Java
> package org.oscm.app.vmware.usage;
> ```

Please add copyright headers 
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 68 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLVILA0RrB-0d_853h:-LjLVILA0RrB-0d_853i:b-u1g5y6) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L68)):*
> ```Java
> 
>         } catch (Exception e) {
>             LOGGER.error("Can´t gather usage data for instance "
> ```

How to handle fatal errors here? Logging is most important, but include the stack trace here. It might be an idea to also set IS_CHARGING=false, if this is a valid circuit breaker - I mean to avoid that the timer permanently re-enters here. Of course it has to be documented in the logs as well, when the error handler changes the value of this user flag. I also suggest to make the message indicate that it's a fatal error, e. g. prefix with "FATAL:"  
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 167 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLXlIWEartP9hodYKB:-LjLXlIWEartP9hodYKC:b-nnmraq) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L167)):*
> ```Java
> 
>     // counter Id's can be different in every vSphere environment, therefore
>     // it,s necessary to map the id's to names
> ```

&#x1F44D; That's valid and good practice for code authors to comment their decisions (instead of their code). Just please use javadoc comment here. 
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_mMa3ZP6d5T249b3:-LjL_mMa3ZP6d5T249b4:b-9fmjg9) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java#L1)):*
> ```Java
> package org.oscm.app.vmware.usage;
> ```

+Copyright headers
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_r2rAE5l4J6c56YW:-LjL_r2rAE5l4J6c56YX:b-xxsdpb) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L1)):*
> ```Java
> package org.oscm.app.vmware.usage;
> ```

+Copyright
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 33 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_9uP7hzc96H58dke:-LjL_9uQAdbKACIKMtw0:b-ck4yr2) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L33)):*
> ```Java
>             .getLogger(VMUsageConverter.class);
> 
>     VMPropertyHandler ph;
> ```

set ph private or (if required for unit testing) - protected 
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 35 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLSc8P9gBH7qFQneus:-LjLSc8P9gBH7qFQneut:b-jbvl0) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L35)):*
> ```Java
>     VMPropertyHandler ph;
>     
>     public VMUsageConverter() {
> ```

Remove default constructor - ph is mandatory

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/37)* status: 7 of 10 files reviewed, 12 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 22 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLa4cp6sWWrKZSyXNm:-LjLa4cp6sWWrKZSyXNn:b4rz0sc) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L22)):*
> ```Java
> import com.vmware.vim25.PerfQuerySpec;
> import com.vmware.vim25.RuntimeFaultFaultMsg;
> ```

+ javadoc class comment about purpose and with @author
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java, line 15 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLabgHA6nwwA-IzRab:-LjLabgHA6nwwA-IzRac:bik2r24) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java#L15)):*
> ```Java
> 
> import com.vmware.vim25.RuntimeFaultFaultMsg;
> ```

+ javadoc
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 23 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLah320HsGCSvxEkHc:-LjLah336mAFFtZRr_aM:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L23)):*
> ```Java
> 
> import com.vmware.vim25.RuntimeFaultFaultMsg;
> ```

dito

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/37)* status: 3 of 10 files reviewed, 12 unresolved discussions (waiting on @GoebelL)

___
*[oscm-app-vmware/resources/TechnicalService_Event.xml, line 5 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLTJs_4LoRIkXkB4EQ:-LjPr6rTAeKzrcw-CdsZ:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/resources/TechnicalService_Event.xml#L5)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Let's use speaking ID, like WMwareSampleWithEvents
</blockquote></details>

Done.
___
*[oscm-app-vmware/resources/TechnicalService_Event.xml, line 916 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLU2Cx6B4OF1_KTWDG:-LjPr7m42ekF4GtGxGZj:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/resources/TechnicalService_Event.xml#L916)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

While looking to the naming, let's fix this name as well. I suggest id="VMware 6.5 Sample" (anything elso ok, but without OSCM version number)
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_eWq4Xec4R7P1GVW:-LjPr9AD39h5WKPzqU7p:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L1)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please add copyright headers 
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 22 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLa4cp6sWWrKZSyXNm:-LjPrDCh-7UUepdDqk5z:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L22)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

+ javadoc class comment about purpose and with @author
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 68 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLVILA0RrB-0d_853h:-LjPrF55BNPkLzEiuLVX:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L68)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

How to handle fatal errors here? Logging is most important, but include the stack trace here. It might be an idea to also set IS_CHARGING=false, if this is a valid circuit breaker - I mean to avoid that the timer permanently re-enters here. Of course it has to be documented in the logs as well, when the error handler changes the value of this user flag. I also suggest to make the message indicate that it's a fatal error, e. g. prefix with "FATAL:"  
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java, line 167 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLXlIWEartP9hodYKB:-LjPrHPh7YQBsNzL7YRn:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMMetricCollector.java#L167)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

&#x1F44D; That's valid and good practice for code authors to comment their decisions (instead of their code). Just please use javadoc comment here. 
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_mMa3ZP6d5T249b3:-LjPrJC39DuQMA7kIGVp:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java#L1)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

+Copyright headers
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java, line 15 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLabgHA6nwwA-IzRab:-LjPrL8h6cLVZ3Y576V8:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageCalculator.java#L15)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

+ javadoc
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 1 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_r2rAE5l4J6c56YW:-LjPrMOmCmsREY8ZkXjt:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L1)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

+Copyright
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 23 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLah320HsGCSvxEkHc:-LjPrNl57wQQ4rvKeLtH:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L23)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 33 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjL_9uP7hzc96H58dke:-LjPrRPq7ZsFYsFQvEQX:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L33)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

set ph private or (if required for unit testing) - protected 
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java, line 35 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/37#-LjLSc8P9gBH7qFQneus:-LjPrTehEHpmXmj2kpyF:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/52ecd9051c27924b39885241cb305c8bcb7e5c4d/oscm-app-vmware/src/main/java/org/oscm/app/vmware/usage/VMUsageConverter.java#L35)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Remove default constructor - ph is mandatory
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/37)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
