### PR TITLE
remove unused buttons

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/42)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/42)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-startup/src/main/webapp/keyValueEditor.xhtml, line 136 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/42#-Lk4lD8v952mu2qt_rDp:-Lk4lD8v952mu2qt_rDq:bxyt1ge) ([raw file](https://github.com/servicecatalog/oscm-app/blob/31baa5249bd8c358aaa6bdb179f9deb7b10c6a49/oscm-app-startup/src/main/webapp/keyValueEditor.xhtml#L136)):*
> ```HTML
> 					onclick=" this.blur(); doShowProgress(true);"
> 					rendered="#{appConfigurationModel.pingButtonVisibilityMap[key]}"
> 					disabled="#{!appConfigurationModel.pingButtonVisibilityMap[key]}"
> ```

Ok, fine. 
Just one point: The disabled condition is superfluous now and better be removed.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/42)* status: all files reviewed, 1 unresolved discussion (waiting on @cworf91)

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/42)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-startup/src/main/webapp/keyValueEditor.xhtml, line 136 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/42#-Lk4lD8v952mu2qt_rDp:-Lk83QKZ8NN-VDDuZxEw:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/31baa5249bd8c358aaa6bdb179f9deb7b10c6a49/oscm-app-startup/src/main/webapp/keyValueEditor.xhtml#L136)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Ok, fine. 
Just one point: The disabled condition is superfluous now and better be removed. 
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
