### PR TITLE
Log4j2 update

### LINKED ISSUE #74: Update Log4j version
**Summary**
Log4j library must be updated to version 2.

**Details**
As the security alert reports, log4j library should be updated - https://github.com/servicecatalog/oscm-app/network/alerts. 

**Acceptance criteria**
- [ ] CVE is fixed
- [ ] logging is working as in current version

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by kowalczyka**
**Changes in this Pull Request:**
- hanges related to log4j library upgrade to version 2
- closes #74 

**Mandatory checks:**
- [x] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [x] changes were tested manually
- [x] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [x] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- OSCM Build And Push job - #586

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/75)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 27 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/75)* status: 27 of 28 files reviewed, 2 unresolved discussions (waiting on @GoebelL and @kowalczyka)

___
*[pom.xml, line 263 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/75#-M2bvEpaAZAA_T3pSXfk:-M2bvEpbEitTxo1AeVbP:b-wr5zjo) ([raw file](https://github.com/servicecatalog/oscm-app/blob/67abe3c9fa80d297661ee99f85b5dc6dfaa03fc6/pom.xml#L263)):*
> ```XML
>                 <groupId>com.github.servicecatalog.oscm-commons</groupId>
>                 <artifactId>oscm-common</artifactId>
>                 <version>log4j_update-SNAPSHOT</version>
> ```

I'd merge your PR in oscm-commons first and take it from master-SNAPSHOT.
___
*[oscm-app/src/test/java/org/oscm/app/business/InitializerTest.java, line 242 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/75#-M2bz7F9BKehIBpHfuSV:-M2bz7F9BKehIBpHfuSW:b-vfv9q2) ([raw file](https://github.com/servicecatalog/oscm-app/blob/67abe3c9fa80d297661ee99f85b5dc6dfaa03fc6/oscm-app/src/test/java/org/oscm/app/business/InitializerTest.java#L242)):*
> ```Java
> 
>   @Test
>   // @Ignore
> ```

Remove comment.

**Comment by GoebelL** [comment]
I guess a log4j2.properties.template file needs to be added for the sample adapter.

**Comment by kowalczyka** [comment]
> I guess a log4j2.properties.template file needs to be added for the sample adapter.

This will be handled in separate issue: #76

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/75)* status: 25 of 28 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[pom.xml, line 263 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/75#-M2bvEpaAZAA_T3pSXfk:-M2c8KKx7jHn5Wy8wCgT:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/67abe3c9fa80d297661ee99f85b5dc6dfaa03fc6/pom.xml#L263)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I'd merge your PR in oscm-commons first and take it from master-SNAPSHOT.
</blockquote></details>

Done.
___
*[oscm-app/src/test/java/org/oscm/app/business/InitializerTest.java, line 242 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/75#-M2bz7F9BKehIBpHfuSV:-M2c8LZlDiM4VGOSrFim:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/67abe3c9fa80d297661ee99f85b5dc6dfaa03fc6/oscm-app/src/test/java/org/oscm/app/business/InitializerTest.java#L242)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Remove comment.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 2 of 28 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/75)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/75#-:-M2h1OcY9xQlVZGyGkqH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/75)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
