### PR TITLE
Add manual provisioning

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/email/ProvisioningEmail.java, line 18 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/68#-LyDdckWECNgX6X2ApEY:-LyDdckWECNgX6X2ApEZ:b-55m26m) ([raw file](https://github.com/servicecatalog/oscm-app/blob/be385cbeec47de6cf2d2edffb2a2e1be010e2f5c/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/email/ProvisioningEmail.java#L18)):*
> ```Java
>  *
>  */
> public class ProvisioningEmail extends TextEmail{
> ```

I don't really see value in deriving such subclass from TextEmail. 
1. The class has no specialization - it's functionally same as its super class. 
2. The manual provisioning process should also support HTML emails.
3. The class name ProvisioningEmail is too general and therefore meaning less, since everything here is about provisioning.

Instead:
- Remove this class 
- Extend org.oscm.app.sample.controller.Email with a method createConfirmationLink, providing for embedding such link in particular email with help of given ProvisioningSettings instance.
- The respective HTML implementation creates content with <a href...>, the text implementaiton https://...
- Add unit test cases in EmailTest

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @cworf91)

___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/email/ProvisioningEmail.java, line 23 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/68#-LyDlLJo5Yzy2MBUyhOQ:-LyDlLJpB1T7jLajXusL:bna7nxj) ([raw file](https://github.com/servicecatalog/oscm-app/blob/be385cbeec47de6cf2d2edffb2a2e1be010e2f5c/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/email/ProvisioningEmail.java#L23)):*
> ```Java
>         super(ps);
>     }
> ```

I don't really see value in deriving such subclass from TextEmail.
1.	The class has no specialization - it's functionally same as its super class.
2.	The manual provisioning process should also support HTML emails.
3.	The class name ProvisioningEmail is too general and therefore meaning less, since everything here is about provisioning.

Instead:
•	Remove this class
•	Extend org.oscm.app.sample.controller.Email with a method createConfirmationLink, providing for embedding such link in particular email with help of given ProvisioningSettings instance.
•	The respective HTML implementation creates content with &lt;a href=... &gt; , the text implementaiton https://...
•	Add unit test cases in EmailTest

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/email/ProvisioningEmail.java, line 23 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/68#-LyDlLJo5Yzy2MBUyhOQ:-LyT67Im8sYwrthTPH-U:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/be385cbeec47de6cf2d2edffb2a2e1be010e2f5c/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/email/ProvisioningEmail.java#L23)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

I don't really see value in deriving such subclass from TextEmail.
1.	The class has no specialization - it's functionally same as its super class.
2.	The manual provisioning process should also support HTML emails.
3.	The class name ProvisioningEmail is too general and therefore meaning less, since everything here is about provisioning.

Instead:
•	Remove this class
•	Extend org.oscm.app.sample.controller.Email with a method createConfirmationLink, providing for embedding such link in particular email with help of given ProvisioningSettings instance.
•	The respective HTML implementation creates content with &lt;a href=... &gt; , the text implementaiton https://...
•	Add unit test cases in EmailTest

</blockquote></details>

Done.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties, line 20 at r3](https://reviewable.io/reviews/servicecatalog/oscm-app/68#-LypdRi90I8JgYs1cBfi:-LypdRi90I8JgYs1cBfj:b-4d3mok) ([raw file](https://github.com/servicecatalog/oscm-app/blob/8b73a77edc9681f195565d1be6ec1fa1ff4c3cc8/oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties#L20)):*
> ```INI
> mail.subject=Sample instance ''{0}'' is currently being provisioned.
> mail.text=The sample instance ''{0}'' is currently being provisioned. Current status: {2}.\n\n {1}
> mail.text.manual.provisioning=Please use the following link to complete the provisioning process: �\n\n�{0}�\n\n�{1} 
> ```

Fix the wrong encodings here.

**Comment by GoebelL** [comment]
@cworf91 
Any update for this PR?

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties, line 20 at r3](https://reviewable.io/reviews/servicecatalog/oscm-app/68#-LypdRi90I8JgYs1cBfi:-M-E_h8R3Zdt3mOSXL9c:b-40iadq) ([raw file](https://github.com/servicecatalog/oscm-app/blob/8b73a77edc9681f195565d1be6ec1fa1ff4c3cc8/oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties#L20)):*
> ```
> mail.text.manual.provisioning will be deleted in the pullrequest #72 
> ```

**Review by GoebelL — APPROVED** [review]
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by cworf91 — COMMENTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 7 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/68)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
