### PR TITLE
Task/customize emails

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/72)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/72)* status: 0 of 11 files reviewed, 8 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-sample/resources/TechnicalService.xml, line 39 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZfV0850S7TlxXH3kT:-LyZfV0850S7TlxXH3kU:b2srn1) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/resources/TechnicalService.xml#L39)):*
> ```XML
>     <ParameterDefinition id="APP_BASE_URL" configurable="true" mandatory="false" valueType="STRING"
>       default="">
>       <LocalizedDescription locale="en">The APP base URL</LocalizedDescription>
> ```

Hmm, the semantic is not obvious here. Consider to rename this parameter.
___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java, line 86 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZoYsc3b-OrbKyV14_:-LyZgAVxBnC14QDpq89m:b-i52mrp) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java#L86)):*
> ```Java
>                     .append("yes");
>         } catch (UnsupportedEncodingException e) {
>             throw new APPlatformException("Failed to create event link.", e);
> ```

- Not an expectable case -> re-throw e in a RuntimeException and remove "throws APPlatf..."
- change "event link" to "confirmation link"
___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/SampleController.java, line 244 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZkcc83VSWwjmHlFKb:-LyZkcc83VSWwjmHlFKc:b5rzhzi) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/SampleController.java#L244)):*
> ```Java
>         InstanceStatus result = null;
>         if (instanceId == null || settings == null || properties == null) {
>             return result;
> ```

Do we really expect to have null values here in any stage? If not, simply remove this if block.
___
*[oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties, line 20 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZgodF4Tq6G5dDFNqK:-LyZgodF4Tq6G5dDFNqL:b-ebid31) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties#L20)):*
> ```INI
> mail.subject=Sample instance ''{0}'' is currently being provisioned.
> mail.text=The sample instance ''{0}'' is currently being provisioned. Current status: {2}.\n\n {1}
> mail.text.manual.provisioning=Please use the following link to complete the provisioning process: �\n\n�{0}�\n\n�{1} 
> ```

This looks garbled. Please check your file encoding. Set UTF-8 in your editor.
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 194 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZhFEcDSNFsl9qzsQC:-LyZhFEcDSNFsl9qzsQD:bmyyw3f) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L194)):*
> ```Java
>   
>     private void assertNoPassword(String body) {
>         Assert.assertFalse(body.contains("PWD"));
> ```

remove Assert and use static imported methods directly.
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 198 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZhitX7QrPiWFbubYB:-LyZhitX7QrPiWFbubYC:b-os88m4) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L198)):*
> ```Java
>     
>     private void assertHTMLConfirmationLink(String result) {
>         Assert.assertEquals(getExpectedHTMLConfirmationLink(), result);
> ```

dito 
remove getExpected.. methods - superfluous as assert methods are self-speaking
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 202 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZhsALE30mhmwWGiHS:-LyZhsALE30mhmwWGiHT:bb7eybp) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L202)):*
> ```Java
> 
>     private void assertConfirmationLink(String result) {
>         Assert.assertEquals(getConfirmationLink(), result);
> ```

dito
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 249 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZkNAk8WrLAi3bHhnX:-LyZkNAk8WrLAi3bHhnY:bb7nb7j) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L249)):*
> ```Java
>         return "<a href=https://fujitsu.com/global/notify?sid=1&controllerid=ess.sample&_resume=yes>";
>     }
> ```

s.o.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/72)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @cworf91)

___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java, line 41 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZrA7g3Xfy2U67vQh_:-LyZrA7g3Xfy2U67vQha:brlccq8) ([raw file](https://github.com/servicecatalog/oscm-app/blob/844c736cc2e6d7a8a4ca883db68c839fb6c90d47/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java#L41)):*
> ```Java
>  */
> public abstract class Email {
> ```

Please check travis failure
https://travis-ci.org/servicecatalog/oscm-app/builds/636973173#L14353

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/72)* status: 0 of 11 files reviewed, 9 unresolved discussions (waiting on @GoebelL)

___
*[oscm-app-sample/resources/TechnicalService.xml, line 39 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZfV0850S7TlxXH3kT:-LycbrgDC4cVGaj4vtsz:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/resources/TechnicalService.xml#L39)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Hmm, the semantic is not obvious here. Consider to rename this parameter.
</blockquote></details>

Done.
___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java, line 86 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZoYsc3b-OrbKyV14_:-LyccBiU5nFsXPQEYPVm:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java#L86)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

- Not an expectable case -> re-throw e in a RuntimeException and remove "throws APPlatf..."
- change "event link" to "confirmation link"

</blockquote></details>

Done.
___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java, line 41 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZrA7g3Xfy2U67vQh_:-LycbusWE0HPBQ8cYkGt:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/844c736cc2e6d7a8a4ca883db68c839fb6c90d47/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/Email.java#L41)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Please check travis failure
https://travis-ci.org/servicecatalog/oscm-app/builds/636973173#L14353
</blockquote></details>

Done.
___
*[oscm-app-sample/src/main/java/org/oscm/app/sample/controller/SampleController.java, line 244 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZkcc83VSWwjmHlFKb:-LyccEkj1gjSwWmW6EoI:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/main/java/org/oscm/app/sample/controller/SampleController.java#L244)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Do we really expect to have null values here in any stage? If not, simply remove this if block.
</blockquote></details>

Done.
___
*[oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties, line 20 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZgodF4Tq6G5dDFNqK:-LyccHlg2KMVd6-5NsuO:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/main/resources/org/oscm/app/sample/i18n/messages_en.properties#L20)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

This looks garbled. Please check your file encoding. Set UTF-8 in your editor.
</blockquote></details>

Done.
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 194 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZhFEcDSNFsl9qzsQC:-LyccKPj8fWw9H2w08eF:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L194)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

remove Assert and use static imported methods directly.
</blockquote></details>

Done.
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 198 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZhitX7QrPiWFbubYB:-LyccyMRAlWDHUbBdguR:bb79qtq) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L198)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

dito 
remove getExpected.. methods - superfluous as assert methods are self-speaking
</blockquote></details>

should the method  name be "getHTMLConfimationLink" or "HTMLConfimationLink"?
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 202 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZhsALE30mhmwWGiHS:-LycdAQI2NtR0jGXmkeP:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L202)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.
___
*[oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java, line 249 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/72#-LyZkNAk8WrLAi3bHhnX:-LycdE8UAt-GnaFGcJJt:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/5085a0dcfb1858288f910a226171aad7859a54a6/oscm-app-sample/src/test/java/org/oscm/app/sample/controller/EmailTest.java#L249)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

s.o.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 4 of 11 files at r1, 1 of 1 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/72)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
