### PR TITLE
Increase coverage in oscm-app package

### PR DESCRIPTION
**Pull request by Piotr-K8i**
**Changes in this Pull Request:**
- add new test in oscm-app package

**Mandatory checks:**
- [ ] latest changes were fetched from the upstream branch before creating this PR (branch is up to date)
- [ ] changes were tested manually
- [ ] unit tests were properly implemented
- [ ] communication about interdependent changes has been sent to the team (if applicable)
- [ ] respective Jenkins jobs were referenced in *additional context* section of this PR

**OSCM Build References:**
- [OSCM Build And Push job](<enter URL to a job here>)
- [OSCM Pull And Start job](<enter URL to a job here>)

---
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104)

### CODE REVIEW

**Review by kowalczyka — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr and @kowalczyka)

___
*[pom.xml, line 187 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/104#-MMFzY7SEZ6epklSD5cj:-MMFzY7SEZ6epklSD5ck:b-bwicrh) ([raw file](https://github.com/servicecatalog/oscm-app/blob/d35c40047f15d16d358c2607b271936cd70b9ac7/pom.xml#L187)):*
> ```XML
>                 <groupId>org.hibernate</groupId>
>                 <artifactId>hibernate-core</artifactId>
>                 <version>5.4.23.Final</version>
> ```

Did you build the oscm-app after this hibernate upgrade and verify that it is working properly?

**Comment by Piotr-K8i** [comment]
> > Reviewed 16 of 17 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104)_ status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr and @kowalczyka)
> 
> _[pom.xml, line 187 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/104#-MMFzY7SEZ6epklSD5cj:-MMFzY7SEZ6epklSD5ck:b-bwicrh) ([raw file](https://github.com/servicecatalog/oscm-app/blob/d35c40047f15d16d358c2607b271936cd70b9ac7/pom.xml#L187)):_
> 
> > ```
> >                 <groupId>org.hibernate</groupId>
> >                 <artifactId>hibernate-core</artifactId>
> >                 <version>5.4.23.Final</version>
> > ```
> 
> Did you build the oscm-app after this hibernate upgrade and verify that it is working properly?

Yes I built. I didn't find any bugs - the pages loaded correctly, and tested functionalities also worked.
Integration tests were also launched, result -> Passed

**Review by kowalczyka — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104#-:-MM_3cfk4q4zxPcibNHT:bnfp4nl)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr and @kowalczyka)

___
*[pom.xml, line 187 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/104#-MMFzY7SEZ6epklSD5cj:-MM_3UOpDGgfxn9gAlGp:bqcvfua) ([raw file](https://github.com/servicecatalog/oscm-app/blob/d35c40047f15d16d358c2607b271936cd70b9ac7/pom.xml#L187)):*
<details><summary><i>Previously, KabacinskiPiotr wrote…</i></summary><blockquote>

Yes I built. I didn't find any bugs - the pages loaded correctly, and tested functionalities also worked. Integration tests were also launched, result -> Passed 
</blockquote></details>

Great, let's give it a try then.

**Review by kowalczyka — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104)* status: all files reviewed, 1 unresolved discussion (waiting on @KabacinskiPiotr)

**Review by Piotr-K8i — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

___
*[pom.xml, line 187 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/104#-MMFzY7SEZ6epklSD5cj:-MM_QySEDJw-3xM7Kgo3:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/43858f03dd3bd850eae6d025f4bc72a91545991b/pom.xml#L187)):*
<details><summary><i>Previously, kowalczyka (Arkadiusz Kowalczyk) wrote…</i></summary><blockquote>

Great, let's give it a try then.
</blockquote></details>

Done.

**Review by kowalczyka — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/104)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
