### PR TITLE
OIDC mode related changes

### PR DESCRIPTION
**Pull request by kowalczyka**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @GoebelL and @kowalczyka)

___
*[oscm-app/src/main/java/org/oscm/app/v2_0/service/APPConfigurationServiceBean.java, line 296 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/49#-Lrr_Ch06xADCv7r5GCf:-Lrr_Ch10_p8jtYChko0:by6hhhf) ([raw file](https://github.com/servicecatalog/oscm-app/blob/8ed33d0ab7431f1a2f83cab084dafd602ed973be/oscm-app/src/main/java/org/oscm/app/v2_0/service/APPConfigurationServiceBean.java#L296)):*
> ```Java
>       // APP_SUSPEND, no handle needed
>     }
>     if (!Strings.isEmpty(isSuspend)) {
> ```

No issue -  just to note: I believe the surrounding condition is redundant here (Boolean.parseBoolean returns false by default).

**Review by GoebelL — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by GoebelL — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)* status: all files reviewed, 1 unresolved discussion (waiting on @kowalczyka)

**Review by kowalczyka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @GoebelL)

___
*[oscm-app/src/main/java/org/oscm/app/v2_0/service/APPConfigurationServiceBean.java, line 296 at r1](https://reviewable.io/reviews/servicecatalog/oscm-app/49#-Lrr_Ch06xADCv7r5GCf:-LrrilJ63syaZHaxw5i8:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/8ed33d0ab7431f1a2f83cab084dafd602ed973be/oscm-app/src/main/java/org/oscm/app/v2_0/service/APPConfigurationServiceBean.java#L296)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

No issue -  just to note: I believe the surrounding condition is redundant here (Boolean.parseBoolean returns false by default).
</blockquote></details>

Done.

**Review by GoebelL — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)* status: all files reviewed, 1 unresolved discussion (waiting on @GoebelL)

**Review by GoebelL — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
