### PR TITLE
Task/set password

### PR DESCRIPTION
**Pull request by cworf91**
This change is [Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/58)

### CODE REVIEW

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/58)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/persistence/APPDataAccessService.java, line 387 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/58#-LvubSH2BwhgeW6wYuBC:-LvubSH39-uIiL823iz4:b-3h38u) ([raw file](https://github.com/servicecatalog/oscm-app/blob/f3b84b5fca409e3cb7e585fc9ae840c86681326c/oscm-app-vmware/src/main/java/org/oscm/app/vmware/persistence/APPDataAccessService.java#L387)):*
> ```Java
>                 p.put(Context.INITIAL_CONTEXT_FACTORY,
>                                     "org.apache.openejb.core.OpenEJBInitialContextFactory");
>                 Context namingContext = new InitialContext(p);
> ```

Some tests may fail as InitialContext constructor was extracted - perhaps for stubbing. Use getNamingContext(p) then.

**Review by GoebelL — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/58)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @cworf91 and @GoebelL)

___
*[oscm-app-vmware/resources/script/Shell_script, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/58#-LvucDzH9HsvqqDp2tJD:-LvucDzH9HsvqqDp2tJE:bp41j6o) ([raw file](https://github.com/servicecatalog/oscm-app/blob/f3b84b5fca409e3cb7e585fc9ae840c86681326c/oscm-app-vmware/resources/script/Shell_script#L1)):*
> ```
> #!/bin/bash
> ```

Remove if not needed.

**Review by cworf91 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/58)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @GoebelL)

___
*[oscm-app-vmware/resources/script/Shell_script, line 1 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/58#-LvucDzH9HsvqqDp2tJD:-LvuhNuu8fZmYvbBTHxG:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/f3b84b5fca409e3cb7e585fc9ae840c86681326c/oscm-app-vmware/resources/script/Shell_script#L1)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Remove if not needed.
</blockquote></details>

Done.
___
*[oscm-app-vmware/src/main/java/org/oscm/app/vmware/persistence/APPDataAccessService.java, line 387 at r2](https://reviewable.io/reviews/servicecatalog/oscm-app/58#-LvubSH2BwhgeW6wYuBC:-LvuhY4JDaAbOkIt6971:b-896fix) ([raw file](https://github.com/servicecatalog/oscm-app/blob/f3b84b5fca409e3cb7e585fc9ae840c86681326c/oscm-app-vmware/src/main/java/org/oscm/app/vmware/persistence/APPDataAccessService.java#L387)):*
<details><summary><i>Previously, GoebelL (Lorenz Goebel) wrote…</i></summary><blockquote>

Some tests may fail as InitialContext constructor was extracted - perhaps for stubbing. Use getNamingContext(p) then.
</blockquote></details>

Done.

**Review by GoebelL — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/servicecatalog/oscm-app/58)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
